### PR TITLE
NBDE lab

### PR DESCRIPTION
**Pull request by sergio-correia**
Add NBDE lab

### CODE REVIEW

**Comment by sergio-correia** [comment]
Rebased after merging of #32

**Comment by sergio-correia** [comment]
Hi @ajacocks, could you please review this PR?

**Review by rjeffman — APPROVED** [review]
LGTM.

**Comment by ggbecker** [comment]
> Add NBDE lab
```
AWS::EC2::Instance nbde2 CREATE_FAILED: The image id '[ami-0b54260f6e56aa856]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound;
```
Sergio can you please make the NBDE image available for other regions as well (all of them I guess)? I'm currently testing on `eu-central-1`.

**Comment by sergio-correia** [comment]
> > Add NBDE lab
> 
> ```
> AWS::EC2::Instance nbde2 CREATE_FAILED: The image id '[ami-0b54260f6e56aa856]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound;
> ```
> 
> Sergio can you please make the NBDE image available for other regions as well (all of them I guess)? I'm currently testing on `eu-central-1`.

I submitted #35 to fix this, thanks @ggbecker

**Pull request merged**
