### PR TITLE
Finalize SELinux lab

### PR DESCRIPTION
**Pull request by wrabcak**
SSIA

### CODE REVIEW

**Comment by wrabcak** [comment]
@ajacocks Please review.

**Comment by ggbecker** [comment]
> @ajacocks Please review.

@ajacocks if you can merge this one first: https://github.com/ajacocks/agnosticd/pull/32

It will introduce conflicts with this PR for sure, but I can help you @wrabcak with the conflict resolving

**Review by ajacocks — APPROVED** [review]
No conflicts that I see.

**Comment by ajacocks** [comment]
Never mind, there they are.

**Comment by ggbecker** [comment]
> Never mind, there they are.

I'll resolve the conflicts and will come up with a solution soon, either closing this one and opening a new one or proposing a pull requests in the original (Lukas' one) fork.

**Review by rjeffman — APPROVED** [review]
LGTM

**Pull request merged**
